// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TomasGreen.Web.Data;

namespace TomasGreen.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180409094013_PurchasedArticleShortageAndContainerDetails")]
    partial class PurchasedArticleShortageAndContainerDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleCategoryID");

                    b.Property<int>("ArticlePackageFormID");

                    b.Property<int>("ArticleUnitID");

                    b.Property<int>("CountryID");

                    b.Property<string>("Description");

                    b.Property<decimal>("MinimumPricePerUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.Property<decimal>("WeightPerPackage")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.HasIndex("ArticleCategoryID");

                    b.HasIndex("ArticlePackageFormID");

                    b.HasIndex("ArticleUnitID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Name", "ArticleUnitID")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ArticleCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ArticlePackageForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ArticlePakageForms");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ArticleUnit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<decimal>("MeasurePerKg")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("MeasuresByG");

                    b.Property<bool>("MeasuresByKg");

                    b.Property<bool>("MeasuresByPiece");

                    b.Property<bool>("MeasuresByTon");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ArticleUnits");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ArticleWarehouseBalance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("QtyExtraIn")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("QtyExtraOnhand")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("QtyExtraOut")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackagesIn");

                    b.Property<int>("QtyPackagesOnhand");

                    b.Property<int>("QtyPackagesOut");

                    b.Property<string>("UserName");

                    b.Property<int>("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("ArticleID", "WarehouseID", "CompanyID")
                        .IsUnique();

                    b.ToTable("ArticleWarehouseBalances");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CreditReceived")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("IsOwner");

                    b.Property<decimal>("LastBalance")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("LastBalanceDate");

                    b.Property<bool>("Locked");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Purchases")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Received")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("Ruble");

                    b.Property<decimal>("SouldToUs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanyCreditDebitBalance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("CurrencyID");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("CompanyID", "CurrencyID")
                        .IsUnique();

                    b.ToTable("CompanyCreditDebitBalances");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanyCreditDebitBalanceDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("BalanceChangerID");

                    b.Property<string>("Comment");

                    b.Property<int>("CompanyCreditDebitBalanceDetailTypeID");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CreditBeforeChange")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("CurrencyID");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("DebitBeforeChange")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PaymentTypeID");

                    b.Property<bool>("RowCreatedBySystem");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyCreditDebitBalanceDetailTypeID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("PaymentTypeID");

                    b.HasIndex("CompanyID", "CurrencyID", "CompanyCreditDebitBalanceDetailTypeID", "BalanceChangerID", "PaymentTypeID")
                        .IsUnique();

                    b.ToTable("CompanyCreditDebitBalanceDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanyCreditDebitBalanceDetailType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("UsedBySystem");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CompanyCreditDebitBalanceDetailTypes");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanySection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Name", "CompanyID")
                        .IsUnique();

                    b.ToTable("CompanySections");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Currency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsBase");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.DicingPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("Date");

                    b.Property<Guid?>("Guid");

                    b.Property<int>("ManagerID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.Property<int>("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("DicingPlans");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.DicingPlanDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<int>("DicingPlanID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.Property<int>("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("DicingPlanID", "WarehouseID", "ArticleID")
                        .IsUnique();

                    b.ToTable("DicingPlanDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<int?>("Age");

                    b.Property<bool>("Archive");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ExternalApi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Link")
                        .IsRequired();

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Provider")
                        .IsRequired();

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Link", "Key")
                        .IsUnique();

                    b.ToTable("ExternalApis");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ExternalApiFunction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ExternalApiID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("ParameterPattern");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("ExternalApiID", "Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("ExternalApiFunctions");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("Archive");

                    b.Property<bool>("Cash");

                    b.Property<string>("Coments");

                    b.Property<int>("CompanyID");

                    b.Property<bool>("Confirmed");

                    b.Property<int>("CurrencyID");

                    b.Property<int>("EmployeeID");

                    b.Property<Guid?>("Guid");

                    b.Property<bool>("HasIssue");

                    b.Property<DateTime?>("LoadedDate");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderNumber");

                    b.Property<bool>("OrderPaid");

                    b.Property<DateTime?>("PaidDate");

                    b.Property<DateTime?>("PaymentDate");

                    b.Property<string>("PaymentWarning");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("TransportFee")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasFilter("[OrderNumber] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<decimal>("Extended_Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Notes");

                    b.Property<int>("OrderID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<string>("UserName");

                    b.Property<int>("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("OrderID", "ArticleID", "WarehouseID", "Price")
                        .IsUnique();

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackagingCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("PackagingCategory");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackagingMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleUnitID");

                    b.Property<string>("Description");

                    b.Property<decimal>("Dimensions")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<int>("PackagingCategoryID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.HasIndex("ArticleUnitID");

                    b.HasIndex("PackagingCategoryID");

                    b.HasIndex("Name", "ArticleUnitID")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("PackagingMaterials");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackingPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("Date");

                    b.Property<Guid?>("Guid");

                    b.Property<int>("ManagerID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("PackingPlans");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackingPlanMix", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("Bags");

                    b.Property<Guid?>("Guid");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("NewArticleID");

                    b.Property<decimal>("NewQtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("NewQtyPackages");

                    b.Property<decimal>("NewTotalWeight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Packages");

                    b.Property<int>("PackagingMaterialBagID");

                    b.Property<int>("PackagingMaterialPackageID");

                    b.Property<int>("PackingPlanID");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("ToWarehouseID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("NewArticleID");

                    b.HasIndex("PackingPlanID");

                    b.HasIndex("ToWarehouseID");

                    b.ToTable("PackingPlanMixs");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackingPlanMixArticle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<decimal>("MixPercent")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PackingPlanMixID");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.Property<int>("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("PackingPlanMixID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("PackingPlanMixArticles");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PaymentType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<bool>("UsedBySystem");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<bool>("Arrived");

                    b.Property<int>("CompanyID");

                    b.Property<int>("CurrencyID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ExpectedToArrive");

                    b.Property<Guid?>("Guid");

                    b.Property<bool>("HasIssue");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("PurchasedArticles");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleContainerDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<string>("ContainerNumber");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PurchasedArticleID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("PurchasedArticleID", "ContainerNumber")
                        .IsUnique()
                        .HasFilter("[ContainerNumber] IS NOT NULL");

                    b.ToTable("PurchasedArticleContainerDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleCostDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("Archive");

                    b.Property<int>("CompanyID");

                    b.Property<int>("CurrencyID");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PurchasedArticleCostTypeID");

                    b.Property<int>("PurchasedArticleID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("PurchasedArticleCostTypeID");

                    b.HasIndex("PurchasedArticleID", "PurchasedArticleCostTypeID", "CompanyID", "CurrencyID")
                        .IsUnique();

                    b.ToTable("PurchasedArticleCostDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleCostType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PurchasedArticleCostTypes");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int?>("ArrivedAtWarehouseID");

                    b.Property<DateTime?>("ArrivedDate");

                    b.Property<int>("ArticleID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Notes");

                    b.Property<int>("PurchasedArticleID");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("QtyExtraArrived")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<int>("QtyPackagesArrived");

                    b.Property<decimal>("TotalPerUnit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.Property<int>("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("ArrivedAtWarehouseID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("PurchasedArticleID", "WarehouseID")
                        .IsUnique();

                    b.ToTable("PurchasedArticleDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleShortageDealingDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("Archive");

                    b.Property<int>("CompanyID");

                    b.Property<int>("CurrencyID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PurchasedArticleID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("PurchasedArticleID", "CompanyID", "CurrencyID")
                        .IsUnique();

                    b.ToTable("PurchasedArticleShortageDealingDetails");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.RoastingPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<int>("Bags");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("FromWarehouseID");

                    b.Property<int>("ManagerID");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("NewArticleID");

                    b.Property<decimal>("NewQtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("NewQtyPackages");

                    b.Property<decimal>("NewTotalWeight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Packages");

                    b.Property<int>("PackagingMaterialBagID");

                    b.Property<int>("PackagingMaterialPackageID");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<decimal>("Salt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SaltLimit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("ToWarehouseID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserName");

                    b.Property<decimal>("WeightChange")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("ArticleID", "Date")
                        .IsUnique();

                    b.ToTable("RoastingPlans");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Address");

                    b.Property<bool>("Archive");

                    b.Property<int?>("CompanySectionID");

                    b.Property<string>("Description");

                    b.Property<bool>("IsCustomers");

                    b.Property<bool>("IsOnTheWay");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Phone");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanySectionID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("TomasGreen.Model.Models.WarehouseToWarehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("Archive");

                    b.Property<int>("ArticleID");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("QtyPackages");

                    b.Property<int>("RecipientCompanyID");

                    b.Property<int>("RecipientWarehouseID");

                    b.Property<int>("SenderCompanyID");

                    b.Property<int>("SenderWarehouseID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("Date", "SenderWarehouseID", "RecipientWarehouseID", "ArticleID")
                        .IsUnique();

                    b.ToTable("WarehouseToWarehouses");
                });

            modelBuilder.Entity("TomasGreen.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TomasGreen.Web.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TomasGreen.Web.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TomasGreen.Web.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TomasGreen.Web.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Article", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.ArticleCategory", "ArticleCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.ArticlePackageForm", "ArticlePackageForm")
                        .WithMany("Articles")
                        .HasForeignKey("ArticlePackageFormID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.ArticleUnit", "ArticleUnit")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleUnitID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Country", "Country")
                        .WithMany("Articles")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ArticleWarehouseBalance", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "Warehouse")
                        .WithMany("ArticleWarehouseBalances")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanyCreditDebitBalance", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanyCreditDebitBalanceDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.CompanyCreditDebitBalanceDetailType", "CompanyCreditDebitBalanceDetailType")
                        .WithMany("CompanyCreditDebitBalanceDetails")
                        .HasForeignKey("CompanyCreditDebitBalanceDetailTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.CompanySection", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany("Sections")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.DicingPlan", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.DicingPlanDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.DicingPlan", "DicingPlan")
                        .WithMany("DicingPlanDetails")
                        .HasForeignKey("DicingPlanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.ExternalApiFunction", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.ExternalApi", "ExternalApi")
                        .WithMany("Functions")
                        .HasForeignKey("ExternalApiID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Order", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany("Orders")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.OrderDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Article", "Article")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "Warehouse")
                        .WithMany("OrderDetails")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackagingMaterial", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.ArticleUnit", "ArticleUnit")
                        .WithMany()
                        .HasForeignKey("ArticleUnitID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PackagingCategory", "PackagingCategory")
                        .WithMany()
                        .HasForeignKey("PackagingCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackingPlanMix", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Article", "NewArticle")
                        .WithMany()
                        .HasForeignKey("NewArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PackingPlan")
                        .WithMany("Mixes")
                        .HasForeignKey("PackingPlanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("ToWarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PackingPlanMixArticle", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PackingPlanMix", "PackingPlanMix")
                        .WithMany("MixArticles")
                        .HasForeignKey("PackingPlanMixID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticle", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleContainerDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.PurchasedArticle", "PurchasedArticle")
                        .WithMany("PurchasedArticleContainerDetails")
                        .HasForeignKey("PurchasedArticleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleCostDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PurchasedArticleCostType", "PurchasedArticleCostType")
                        .WithMany()
                        .HasForeignKey("PurchasedArticleCostTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PurchasedArticle", "PurchasedArticle")
                        .WithMany("PurchasedArticleCostDetails")
                        .HasForeignKey("PurchasedArticleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Warehouse", "ArrivedAtWarehouse")
                        .WithMany()
                        .HasForeignKey("ArrivedAtWarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PurchasedArticle", "PurchasedArticle")
                        .WithMany("PurchasedArticleDetails")
                        .HasForeignKey("PurchasedArticleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Warehouse", "OntheWayWarehouse")
                        .WithMany("PurchasedArticleDetails")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.PurchasedArticleShortageDealingDetail", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.PurchasedArticle", "PurchasedArticle")
                        .WithMany("PurchasedArticleShortageDealingDetails")
                        .HasForeignKey("PurchasedArticleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.RoastingPlan", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TomasGreen.Model.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TomasGreen.Model.Models.Warehouse", b =>
                {
                    b.HasOne("TomasGreen.Model.Models.CompanySection", "Section")
                        .WithMany()
                        .HasForeignKey("CompanySectionID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
